#!/bin/bash
> timesPhilo.csv
for n in {2..16}
do
	for i in {1..5}
	do
		/usr/bin/time -a -o "timesPhilo.csv" -f '%e,' ./philo $n
		truncate -s-1 timesPhilo.csv
	done
	truncate -s-1 timesPhilo.csv
	echo "" >> timesPhilo.csv
done
