#!/bin/bash
> timesLectEcr.csv
for i in {1..5}
	echo -n "$i," >> timesLectEcr.csv
	echo "" >> timesLectEcr.csv
done
for n in {1..8}
do
	for i in {1..5}
	do
		let n2=n-1
		/usr/bin/time -a -o "timesLectEcr.csv" -f '%e,' ./lectEcr $n $n2
		truncate -s-1 timesLectEcr.csv
	done
	truncate -s-1 timesLectEcr.csv
	echo "" >> timesLectEcr.csv
	for i in {1..5}
	do
		/usr/bin/time -a -o "timesLectEcr.csv" -f '%e,' ./lectEcr $n $n
                truncate -s-1 timesLectEcr.csv
	done
	truncate -s-1 timesLectEcr.csv
        echo "" >> timesLectEcr.csv
done
