#!/bin/bash
> timesAsmPhilo.csv
for i in {1..5}
do
        echo -n "$i," >> timesAsmPhilo.csv
done
echo "" >> timesAsmPhilo.csv
for n in {1..16}
do
	for i in {1..5}
	do
		/usr/bin/time -a -o "timesAsmPhilo.csv" -f '%e,' ./asmPhilo $n
		truncate -s-1 timesAsmPhilo.csv
	done
	truncate -s-1 timesAsmPhilo.csv
	echo "" >> timesAsmPhilo.csv
done
