#!/bin/bash
> ./results/timesLectEcr.csv
for i in {1..5}
do
	echo -n "$i," >> ./results/timesLectEcr.csv
done
echo "" >> ./results/timesLectEcr.csv
for n in {1..8}
do
	for i in {1..5}
	do
		let n2=n-1
		/usr/bin/time -a -o "./results/timesLectEcr.csv" -f '%e,' ./lectEcr $n2 $n
		truncate -s-1 ./results/timesLectEcr.csv
	done
	truncate -s-1 ./results/timesLectEcr.csv
	echo "" >> ./results/timesLectEcr.csv
	for i in {1..5}
	do
		/usr/bin/time -a -o "./results/timesLectEcr.csv" -f '%e,' ./lectEcr $n $n
                truncate -s-1 ./results/timesLectEcr.csv
	done
	truncate -s-1 ./results/timesLectEcr.csv
        echo "" >> ./results/timesLectEcr.csv
done
